export const TipsURL = import.meta.env.VITE_SERVER_URL_TIPS || "https://greenliving-rmz5.onrender.com/tips"
export const ResourceURL = import.meta.env.VITE_SERVER_URL_RESOURCES || "https://greenliving-rmz5.onrender.com/resources"
export const loginURL = import.meta.env.VITE_SERVER_URL_USER_LOGIN || "https://greenliving-rmz5.onrender.com/users/login"
export const infoURL = import.meta.env.VITE_SERVER_URL_USER_INFO || "https://greenliving-rmz5.onrender.com/users/getInfo"
export const registerURL = import.meta.env.VITE_SERVER_URL_USER_REGISTER || "https://greenliving-rmz5.onrender.com/users/register"
export const footPrintURL = import.meta.env.VITE_SERVER_URL_FOOTPRINT || "https://greenliving-rmz5.onrender.com/carbonFootprint"